sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      env:
        C_COMPILER=gcc-4.8
        CXX_COMPILER=g++-4.8
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        C_COMPILER=gcc-4.9
        CXX_COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        C_COMPILER=gcc-5
        CXX_COMPILER=g++-5
    - compiler: clang
      env:
        C_COMPILER=clang-3.5
        CXX_COMPILER=clang++-3.5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        C_COMPILER=clang-3.6
        CXX_COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        C_COMPILER=clang-3.7
        CXX_COMPILER=clang++-3.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake libboost-test-dev gcov lcov gcovr
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=`which ${C_COMPILER}` -DCMAKE_CXX_COMPILER=`which ${CXX_COMPILER}` ../src && make coverage
