#ifndef SAMPLING_ENGINE_RECORD_TYPE_H__
#define SAMPLING_ENGINE_RECORD_TYPE_H__

namespace samplingEngine
    {
    namespace records
        {
        //! Data Record Type
        /*!
         There are several different data records used by and generated by the
         Sample Engine. Each has a specific purpose and use.
         */
        enum recordType
            {
            INVALID_RECORD_TYPE=0,  /*!< Invalid Data Record */
            TIME_RECORD_TYPE,       /*!< Time Sample Record */
            STATUS_RECORD_TYPE,     /*!< Channel Status Record */
            DISTANCE_RECORD_TYPE,   /*!< Distance Sample Record */
            };
        }
    }

#endif //SAMPLING_ENGINE_RECORD_TYPE_H__
