name: Sampling Engine - CI
on: [ pull_request ]
jobs:
  build:
     name: Build 
     runs-on: ubuntu-18.04 
     strategy:
       fail-fast: true
       matrix:
         COMPILER_SUITE: [gcc, clang]
         C_COMPILER_VERSION: [gcc-4.8, gcc-4.9, gcc-5, clang-3.5, clang-3.6, clang-3.7] 
         CXX_COMPILER_VERSION: [g++-4.8, g++-4.9, g++-5, clang++-3.5, clang++-3.6, clang++-3.7] 
         COMPILER_PACKAGE: [g++-4.8, g++-4.9, g++-5, clang-3.5, clang-3.6, clang-3.7]
         include:
           - COMPILER_SUITE: gcc
             C_COMPILER_VERSION: gcc-4.8
             CXX_COMPILER_VERSION: g++-4.8
             COMPILER_PACKAGE: g++-4.8
           - COMPILER_SUITE: gcc
             C_COMPILER_VERSION: gcc-4.9
             CXX_COMPILER_VERSION: g++-4.9
             COMPILER_PACKAGE: g++-4.9
           - COMPILER_SUITE: gcc
             C_COMPILER_VERSION: gcc-5
             CXX_COMPILER_VERSION: g++-5
             COMPILER_PACKAGE: g++-5
           - COMPILER_SUITE: clang
             C_COMPILER_VERSION: clang-3.5
             CXX_COMPILER_VERSION: clang++-3.5
             COMPILER_PACKAGE: clang-3.5
           - COMPILER_SUITE: clang
             C_COMPILER_VERSION: clang-3.6
             CXX_COMPILER_VERSION: clang++-3.6
             COMPILER_PACKAGE: clang-3.6
           - COMPILER_SUITE: clang
             C_COMPILER_VERSION: clang-3.7
             CXX_COMPILER_VERSION: clang++-3.7
             COMPILER_PACKAGE: clang-3.7
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
       - name: Move to PR Head
         run: git checkout HEAD^2
       - name: Update APT Cache 
         run: sudo apt-get update -qq
       - name: Install dependencies
         run: sudo apt-get -y install cmake libboost-test-dev lcov gcovr ${{ matrix.COMPILER_PACKAGE }}
       - name: Install Coveralls (GCC only)
         run: pip install --user cpp-coveralls
         if: ${{ matrix.COMPILER_SUITE }} == "gcc"
       - name: create build directory
         run: mkdir build
       - name: Build
         env:
           C_COMPILER: ${{ matrix.C_COMPILER_VERSION }}
           CXX_COMPILER: ${{ matrix.CXX_COMPILER_VERSION }}
         run: cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=`which ${C_COMPILER}` -DCMAKE_CXX_COMPILER=`which ${CXX_COMPILER}` ../src 
       - name: Build with Coverage (GCC compilers only)
         run: cd build && make coverage && coveralls --exclude lib --exclude tests --gcov-options '\-lpr'
         if: ${{ matrix.COMPILER_SUITE }} == "gcc"
       - name: Build without Coverage (non-GCC compilers)
         run: cd build && make && make test
         if: ${{ matrix.COMPILER_SUITE }} != "gcc"
       #- name: Post Coveralls Data
       #  run: coveralls --exclude lib --exclude tests --gcov-options '\-lpr'
       #  if: ${{ matrix.COMPILER_SUITE }} == "gcc"
